version: '3.8'

services:
  backend:
    build: ./backend
    working_dir: /usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:pgpass@db/holacircle
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    ports:
      - 5001:8000
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app:cached
      - rust_cargo:/usr/local/cargo/registry
      - rust_target:/usr/src/app/target
    command: sh ./start_development.sh
  frontend:
    build: ./frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app:cached
    ports:
      - 5000:3000
    depends_on:
      - backend
    command: sh ./start_development.sh
    tty: true
    stdin_open: true
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgpass

volumes:
  rust_target:
  rust_cargo:
  db_data:
